### PR TITLE
[KNUDEV-7] added department creation logics and tests for it

### LINKED ISSUE #7: Create account controller
1. Create account registration request with validation for reg. endpoint
2. Create registration endpoint in rest module
3. Create account service with api for account persistance
4. Create account get endpoint
5. Create custom exception for account exception and rest exception handler ( optional , if needed )

### PR DESCRIPTION
**Pull request by DenysLnk**

### CODE REVIEW

File: team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/dto/DepartmentDto.java [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+@Builder
+public record DepartmentDto(
+        UUID id,
+        @NotBlank(message = "Department name can`t be empty")
+        @NotNull(message = "Department name cant be null")
+        String name,
+        @NotEmpty(message = "Specialties collection can`t be empty")
+        Set<@Valid SpecialtyCreationDto> specialties
+) {
+}
```
Comment (cumbainer) [inline team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/dto/DepartmentDto.java:15]: remove all validations from here

File: team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+import java.util.Set;
+import java.util.UUID;
+
+@Builder
+@Validated
+public record DepartmentCreationRequest(
+        UUID id,
+        @NotNull(message = "Department name cannot be blank or empty")
+        @NotBlank(message = "Department name cannot be blank or empty")
+        String name,
```
Comment (cumbainer) [inline team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java]: Replace notNull and notBlank with this

@NotBlank(message = "Department name cannot be blank or empty.")
        @Size(min = 3, max = 100, message = "Too long or short department name.")
        @Pattern(regexp = "^[A-Za-zА-Яа-яЇїІіЄєҐґ\\s-]+$", message = "Department name contains invalid characters.")

File: team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+        @NotEmpty(message = "Specialties collection cannot be empty")
+        Set<@Valid SpecialtyCreationDto> specialties
```
Comment (cumbainer) [inline team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java:27]: @NotEmpty(message = "Department must contain specialties")
        @Min(value=2, message="Department must contain at least 2 specialties")
        @Max(value=50, message="Too much specialties in department")
        Set<@Valid SpecialtyCreationDto> specialties

File: team-manager/src/main/java/ua/knu/knudev/teammanager/domain/Department.java [hunk 4]
```diff
@@ -35,7 +35,12 @@ public class Department {
     private Set<Specialty> specialties = new HashSet<>();
 
     public void addSpecialty(Specialty specialty) {
-        this.specialties.add(specialty);
-        specialty.getDepartments().add(this);
+        if (specialty != null) {
+            this.specialties.add(specialty);
+            specialty.getDepartments().add(this);
+        } else {
+            throw new IllegalArgumentException("Specialty cannot be null");
```
Comment (cumbainer) [inline team-manager/src/main/java/ua/knu/knudev/teammanager/domain/Department.java]: Throw here DepartmentException

File: team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+import jakarta.validation.constraints.NotNull;
+import lombok.Builder;
+import org.springframework.validation.annotation.Validated;
+import ua.knu.knudev.teammanagerapi.dto.SpecialtyCreationDto;
+
+import java.util.Set;
+import java.util.UUID;
+
+@Builder
+@Validated
```
Comment (cumbainer) [inline team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java]: remove this

File: team-manager/src/main/java/ua/knu/knudev/teammanager/mapper/SpecialtyMapper.java [hunk 6]
```diff
@@ -0,0 +1,10 @@
+package ua.knu.knudev.teammanager.mapper;
+
+import org.mapstruct.Mapper;
+import ua.knu.knudev.knudevcommon.mapper.BaseMapper;
+import ua.knu.knudev.teammanager.domain.Specialty;
+import ua.knu.knudev.teammanagerapi.dto.SpecialtyCreationDto;
+
+@Mapper(componentModel = "spring")
+public interface SpecialtyMapper extends BaseMapper<Specialty, SpecialtyCreationDto> {
```
Comment (cumbainer) [inline team-manager/src/main/java/ua/knu/knudev/teammanager/mapper/SpecialtyMapper.java]: SpecialtyCreationDto is not the DTO. Either build domain by hand, or put here Dto. But it must be something like 
public interface SpecialtyMapper extends BaseMapper<Specialty, SpecialtyDto>

File: team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/dto/SpecialtyCreationDto.java [hunk 7]
```diff
@@ -0,0 +1,15 @@
...
+
+@Builder
+public record SpecialtyCreationDto(
+        @NotNull(message = "Specialty code-name cant be null or 0")
+        Double codeName,
+        @NotBlank(message = "Specialty name can`t be blank")
+        @NotNull(message = "Specialty name can`t be null")
+        String name
+) {
+}
```
Comment (cumbainer) [inline team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/dto/SpecialtyCreationDto.java:26]: Mark fields like
@NotNull(message = "Specialty code-name cannot be null.")
        @Positive(message = "Specialty code must be greater than 0.")
        Double codeName,

   
        @NotNull(message = "Specialty name cannot be empty.")
 @NotNull(message = "Specialty name cannot be blank.")
        @Size(min = 2, max = 200, message = "Specialty name must be between 2 and 200 characters.")
        @Pattern(regexp = "^[A-Za-zА-Яа-яЇїІіЄєҐґ\\s-]+$", message = "Specialty name contains invalid characters.")
        String name

File: team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java [hunk 8]
```diff
@@ -1,21 +1,43 @@
...
 @RequiredArgsConstructor
-public class DepartmentService {
+@Validated
+public class DepartmentService implements DepartmentApi {
 
     private final DepartmentRepository departmentRepository;
 
+    @Override
+    public void createDepartment(@Valid DepartmentCreationRequest departmentCreationRequest) {
+        Department department = new Department();
```
Comment (cumbainer) [inline team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java]: check here in another method `existsById(UUID id)` that department already exists, in that method throw department exception

**Review by cumbainer — CHANGES_REQUESTED** [review]

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java [hunk 9]
```diff
@@ -151,4 +157,163 @@ void should_throwDepartmentException_When_DepartmentDoesNotExistOnGet() {
 
         verify(departmentRepository, times(1)).findById(TEST_DEPARTMENT_ID);
     }
+
+    @Test
+    @DisplayName("Should create department when given valid data")
+    public void should_createDepartment_When_givenValidData() {
+        SpecialtyCreationDto specialtyCreationDto1 = new SpecialtyCreationDto(14.378, "Computer Engineering");
+        SpecialtyCreationDto specialtyCreationDto2 = new SpecialtyCreationDto(14.378, "Radio technics");
+        SpecialtyCreationDto specialtyCreationDto3 = new SpecialtyCreationDto(14.378, "History");
```
Comment (cumbainer) [inline team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: use here method getTestSpecialty(name)

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java [hunk 10]
```diff
@@ -151,4 +157,163 @@ void should_throwDepartmentException_When_DepartmentDoesNotExistOnGet() {
...
+                ConstraintViolationException.class, () -> {
+                    departmentService.createDepartment(departmentCreationRequest);
+                });
+
+        assertEquals("Department name cannot be blank or empty", constraintViolationException.getMessage());
+    }
+
+    @Test
+    @DisplayName("Should not create department when department name is blank")
+    public void should_notCreateDepartment_When_departmentNameIsBlank() {
```
Comment (cumbainer) [inline team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: Validation tests are not need here. We can remove them or move to integration tests ( which is better i guess ). And add 1 more test when department already exists

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java [hunk 11]
```diff
@@ -151,4 +157,163 @@ void should_throwDepartmentException_When_DepartmentDoesNotExistOnGet() {
 
         verify(departmentRepository, times(1)).findById(TEST_DEPARTMENT_ID);
     }
+
+    @Test
+    @DisplayName("Should create department when given valid data")
+    public void should_createDepartment_When_givenValidData() {
+        SpecialtyCreationDto specialtyCreationDto1 = new SpecialtyCreationDto(14.378, "Computer Engineering");
```
Comment (cumbainer) [inline team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: Put here Arrange, Act, Assert comments for better readability, because test is kind of large

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java [hunk 12]
```diff
@@ -151,4 +157,163 @@ void should_throwDepartmentException_When_DepartmentDoesNotExistOnGet() {
...
+
+        DepartmentCreationRequest departmentCreationRequest = buildDepartmentCreationRequest(
+                Set.of(specialtyCreationDto1, specialtyCreationDto2, specialtyCreationDto3),
+                TEST_DEPARTMENT_NAME
+        );
+
+        departmentService.createDepartment(departmentCreationRequest);
+
+        ArgumentCaptor<Department> departmentCaptor = ArgumentCaptor.forClass(Department.class);
+        verify(departmentRepository, times(1)).save(departmentCaptor.capture());
```
Comment (cumbainer) [inline team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: And put please this verify to the bottom, because our convention is all verifies are at the bottom

**Review by cumbainer — CHANGES_REQUESTED** [review]

File: team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/dto/DepartmentDto.java (hunk 1 above)
Comment (DenysLnk) [reply team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/dto/DepartmentDto.java:15]: deleted

File: team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java (hunk 2 above)
Comment (DenysLnk) [reply team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java]: changed

File: team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java (hunk 3 above)
Comment (DenysLnk) [reply team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java:27]: changed

File: team-manager/src/main/java/ua/knu/knudev/teammanager/domain/Department.java (hunk 4 above)
Comment (DenysLnk) [reply team-manager/src/main/java/ua/knu/knudev/teammanager/domain/Department.java]: done

File: team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java (hunk 5 above)
Comment (DenysLnk) [reply team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java]: has deleted yet

File: team-manager/src/main/java/ua/knu/knudev/teammanager/mapper/SpecialtyMapper.java (hunk 6 above)
Comment (DenysLnk) [reply team-manager/src/main/java/ua/knu/knudev/teammanager/mapper/SpecialtyMapper.java]: done

File: team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/dto/SpecialtyCreationDto.java (hunk 7 above)
Comment (DenysLnk) [reply team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/dto/SpecialtyCreationDto.java:26]: done

File: team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java (hunk 8 above)
Comment (DenysLnk) [reply team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java]: done

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java (hunk 9 above)
Comment (DenysLnk) [reply team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: no? because i need here creationDto not Domain

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java (hunk 10 above)
Comment (DenysLnk) [reply team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java:214]: done

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java (hunk 11 above)
Comment (DenysLnk) [reply team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: done

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java (hunk 12 above)
Comment (DenysLnk) [reply team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: ok

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java (hunk 9 above)
Comment (cumbainer) [reply team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: Yes. Its actually better to just instantiate via `new` keyword

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java [hunk 13]
```diff
@@ -23,9 +28,10 @@
 @ExtendWith(MockitoExtension.class)
 class DepartmentServiceTest {
 
-    private static final Department TEST_DEPARTMENT = getTestDepartment();
     private static final Double TEST_SPECIALTY_ID = DepartmentTestsConstants.TEST_SPECIALTY_ID;
     private static final UUID TEST_DEPARTMENT_ID = DepartmentTestsConstants.TEST_DEPARTMENT_ID;
+    private final UUID testDepartmentID = UUID.randomUUID();
```
Comment (cumbainer) [inline team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: we already have variable `TEST_DEPARTMENT_ID`

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java [hunk 14]
```diff
@@ -23,9 +28,10 @@
...
+    private static final String TEST_DEPARTMENT_NAME = "Test Department";
```
Comment (cumbainer) [inline team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: Put this to `DepartmentTestsConstants` if it doesnt exist already

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java [hunk 15]
```diff
@@ -151,4 +157,159 @@ void should_throwDepartmentException_When_DepartmentDoesNotExistOnGet() {
...
+        Department savedDepartment = departmentCaptor.getValue();
+
+        assertEquals(TEST_DEPARTMENT_NAME, savedDepartment.getName());
+        assertEquals(3, savedDepartment.getSpecialties().size());
+
+        assertTrue(savedDepartment.getSpecialties().stream()
+                .anyMatch(specialty -> "Computer Engineering".equals(specialty.getName())));
+        assertTrue(savedDepartment.getSpecialties().stream()
+                .anyMatch(specialty -> "Radio technics".equals(specialty.getName())));
+        assertTrue(savedDepartment.getSpecialties().stream()
```
Comment (cumbainer) [inline team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: Instead of 3 separate asserts. Make 1 assert with allMatch. And for later reasosns, put this 3 specialties names to enums in class `DepartmentTestsConstants`. And it will be better to rename it `AcademicUnitsTestsConstants`

**Review by cumbainer — CHANGES_REQUESTED** [review]

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java (hunk 13 above)
Comment (DenysLnk) [reply team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: deleted

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java (hunk 14 above)
Comment (DenysLnk) [reply team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: delete

File: team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java (hunk 15 above)
Comment (DenysLnk) [reply team-manager/src/test/unit/java/ua/knu/knudev/teammanager/service/DepartmentServiceTest.java]: done

File: team-manager/src/main/java/ua/knu/knudev/teammanager/repository/SpecialtyRepository.java [hunk 16]
```diff
@@ -0,0 +1,10 @@
+package ua.knu.knudev.teammanager.repository;
+
+import org.springframework.data.jpa.repository.JpaRepository;
+import ua.knu.knudev.teammanager.domain.Specialty;
+
+public interface SpecialtyRepository extends JpaRepository<Specialty, Double> {
+
+    boolean existsById(Double id);
```
Comment (cumbainer) [inline team-manager/src/main/java/ua/knu/knudev/teammanager/repository/SpecialtyRepository.java]: existsByCodeName, we dont have an id in specialty

File: team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java [hunk 17]
```diff
@@ -1,20 +1,57 @@
...
+public class DepartmentService implements DepartmentApi {
 
     private final DepartmentRepository departmentRepository;
+    private final SpecialtyRepository specialtyRepository;
+
+    @Override
+    public void createDepartment(DepartmentCreationRequest departmentCreationRequest) {
+        Department department = new Department();
+        String departmentCreationName = departmentCreationRequest.name();
+        Set<@Valid SpecialtyCreationDto> specialties = departmentCreationRequest.specialties();
```
Comment (cumbainer) [inline team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java]: Remove @Valid from here, it doesnt do anything on this stage

File: team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java [hunk 18]
```diff
@@ -0,0 +1,20 @@
...
+import lombok.Builder;
+import ua.knu.knudev.teammanagerapi.dto.SpecialtyCreationDto;
+
+import java.util.Set;
+
+@Builder
+public record DepartmentCreationRequest(
+        @NotEmpty(message = "Department name cannot be blank or empty.")
+        @Size(min = 3, max = 150, message = "Too long or short department name.")
+        @Pattern(regexp = "^[A-Za-zА-Яа-яЇїІіЄєҐґ\s-]+$", message = "Department name contains invalid characters.")
```
Comment (cumbainer) [inline team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java]: make and test pattern only for ukrainan language. And put message that department name must contain only urkainain characters

**Review by cumbainer — CHANGES_REQUESTED** [review]

File: team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java [hunk 19]
```diff
@@ -1,20 +1,57 @@
...
+
+        boolean departmentAlreadyInDb = existByName(departmentCreationName);
+        if (departmentAlreadyInDb) {
+            throw new DepartmentException("Department with name" + departmentCreationName + "already exists");
+        }
```
Comment (cumbainer) [inline team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java]: I propose to extract this whole logic from line 33 to 36 to another method
 `private void assertDepartmentDoesNotExist(String departmentName)`

File: team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java [hunk 20]
```diff
@@ -1,20 +1,57 @@
...
 @Service
 @RequiredArgsConstructor
-public class DepartmentService {
+public class DepartmentService implements DepartmentApi {
 
     private final DepartmentRepository departmentRepository;
+    private final SpecialtyRepository specialtyRepository;
+
+    @Override
+    public void createDepartment(DepartmentCreationRequest departmentCreationRequest) {
```
Comment (cumbainer) [inline team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java]: You should before all logic handle the input
If i type 2 specialties with same names and different code  names - i should get 401 error code
If i type 2 specialties with diffrenent names but same codenames - i shoould get 401 error

So specialties must be distinct by all fields. 
Only after that should be check that department must be non-existent ( obviously ), as it is now

File: team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java [hunk 21]
```diff
@@ -1,20 +1,57 @@
...
+        Department department = new Department();
+        String departmentCreationName = departmentCreationRequest.name();
+        Set<@Valid SpecialtyCreationDto> specialties = departmentCreationRequest.specialties();
+
+        boolean departmentAlreadyInDb = existByName(departmentCreationName);
+        if (departmentAlreadyInDb) {
+            throw new DepartmentException("Department with name" + departmentCreationName + "already exists");
+        }
+
+        List<Specialty> allSpecialtiesInDb = specialtyRepository.findAll();
```
Comment (cumbainer) [inline team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java]: This is not a good idea to find all specialties. KNU has ~ 500 specialties. 
You can use JPA method 
`List<Specialty> findSpecialtiesByCodeNameInOrNameIn(Set<Double> codeNames, Set<String> names);`

**Review by cumbainer — CHANGES_REQUESTED** [review]

File: team-manager/src/main/java/ua/knu/knudev/teammanager/repository/SpecialtyRepository.java (hunk 16 above)
Comment (DenysLnk) [reply team-manager/src/main/java/ua/knu/knudev/teammanager/repository/SpecialtyRepository.java]: done

File: team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java (hunk 17 above)
Comment (DenysLnk) [reply team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java]: done

File: team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java (hunk 18 above)
Comment (DenysLnk) [reply team-manager-api/src/main/java/ua/knu/knudev/teammanagerapi/request/DepartmentCreationRequest.java]: done

File: team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java (hunk 19 above)
Comment (DenysLnk) [reply team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java]: done

File: team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java (hunk 20 above)
Comment (DenysLnk) [reply team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java]: done

File: team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java (hunk 21 above)
Comment (DenysLnk) [reply team-manager/src/main/java/ua/knu/knudev/teammanager/service/DepartmentService.java]: done
